kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ssb-pvc-extended
  namespace: scuttlebutt
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: do-block-storage
